services:
  - type: web
    name: mi-cv-profesional
    env: python
    plan: free
    buildCommand: |
      cd chatcv/frontend/document-chat-app && npm install && npm run build
      mkdir -p chatcv/backend/static
      cp -r chatcv/frontend/document-chat-app/build * chatcv/backend/static/
      cd chatcv/backend && pip install -r requirements.txt
    startCommand: "cd chatcv/backend && gunicorn app:app"
    autoDeploy: true
    region: oregon
    branch: master