services:
  - type: web
    name: mi-cv-profesional
    env: python
    plan: free
    buildCommand: |
      # 1. Construir el frontend
      cd chatcv/frontend/document-chat-app && npm install && npm run build
      
      # 2. Copiar la build al backend
      mkdir -p ../../backend/static
      cp -r build/* ../../backend/static/
      
      # 3. Instalar dependencias del backend
      cd ../../backend && pip install -r requirements.txt
    startCommand: "cd chatcv/backend && gunicorn app:app"
    autoDeploy: true
    region: oregon
    branch: master